// react-html/src/pages/Login.tsx
import { Avatar, Button, Grid, Hidden, TextField, Typography } from '@material-ui/core';
import React from 'react';
import { Link } from 'react-router-dom';
import { ICPassword, ICUsername, LoginBG, LoginLogo } from '../assets/images';
import { Helmet } from 'react-helmet';

function Login() {
    return (
        <>
            <Helmet>
                <title>Login</title>
            </Helmet>
            {/* Login Wrapper Start */}
            <div className="login-wrapper">
                <Grid container>
                    <Grid item xs>

                        {/* Left Part Start */}
                        <div className="login-left">
                            <Link to={'Login'} title="Company Logo" className="logo">
                                <Avatar variant="square" src={LoginLogo} />
                            </Link>
                            <form action="#" className="login-form">
                                <Typography variant="h3">Welcome to Company!</Typography>
                                <Typography variant="h5">Please login to your account</Typography>
                                <div className="form-control">
                                    <TextField label="Username" variant="outlined" />
                                    <Avatar variant="square" src={ICUsername} />
                                </div>
                                <div className="form-control">
                                    <TextField label="Password" variant="outlined" type="password" />
                                    <Avatar variant="square" className="password-icon" src={ICPassword} />
                                </div>
                                <div className="middle">
                                    <Button variant="contained" color="primary" to="/Dashboard" component={Link} disableElevation>Login</Button>
                                    <Link to={'Login'} title="Login" className="forgot-link">Forgot Password?</Link>
                                </div>
                                <Typography variant="body1">Don’t have an account?<Link to={'Login'} title="Sign Up">Sign Up</Link></Typography>
                            </form>
                        </div>
                    </Grid>
                    {/* Left Part End */}

                    {/* Right Part Start */}
                    <Hidden xsDown>
                        <Grid item xs>
                            <div className="login-right">
                                <div className="banner">
                                    <Avatar variant="square" src={LoginBG} alt="We are here" />
                                </div>
                                <div className="content">
                                    <Typography variant="h3">We are here!</Typography>
                                    <Typography variant="body1">Lorem ipsum dolor sit amet concectetur.</Typography>
                                </div>
                            </div>
                        </Grid>
                    </Hidden>
                    {/* Right Part End */}
                </Grid>
            </div>
            {/* Login Wrapper End */}
        </>
    );
};

export default Login;

// angular-html/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Title } from '@angular/platform-browser';
import {
  trigger,
  style,
  transition,
  query,
  stagger,
  useAnimation,
} from '@angular/animations';
import { fadeInAnimation, fadeUpAnimation } from 'src/app/animation';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: [],
  animations: [
    trigger('animationIn', [
      transition(':enter', [
        query('.animation-fadeIn', [
          style({ opacity: '0' }),
          stagger(120, [
            useAnimation(fadeInAnimation, { params: { duration: '0.4s', delay: '0.3s' } })
          ])
        ])
      ])
    ]),
    trigger('animationChildIn', [
      transition(':enter', [
        query('.animation-target', [
          style({ opacity: '0' }),
          stagger(120, [
            useAnimation(fadeUpAnimation, { params: { duration: '0.6s', delay: '0.3s', offset: '50px' } })
          ])
        ])
      ]),
    ]),
  ]
})
export class LoginComponent implements OnInit {

  constructor(public titleService: Title) {
    this.titleService.setTitle("Login");
  }

  ngOnInit(): void {
  }

}

<div class="row g-0">
    <!-- Login Left Start-->
    <div class="col">
        <div class="login-left" [@animationIn] [@animationChildIn]>
            <a href="index.html" title="Company Logo" aria-label="Logo" class="logo animation-fadeIn">
                <img src="./assets/images/login-logo.png" alt="Company Logo">
            </a>
            <form action="#" class="login-form">
                <h3 class="animation-target">Welcome to Company!</h3>
                <h5 class="animation-target">Please login to your account</h5>
                <mat-form-field appearance="outline" class="animation-target">
                    <img src="./assets/images/ic-user.svg" alt="Username">
                    <mat-label>Username</mat-label>
                    <input matInput>
                </mat-form-field>
                <mat-form-field appearance="outline" class="animation-target">
                    <img src="./assets/images/ic-password.svg" alt="Password" class="password-icon">
                    <mat-label>Password</mat-label>
                    <input matInput type="password">
                </mat-form-field>
                <div class="middle animation-target">
                    <a mat-flat-button title="Login" routerLink="/dashboard" color="primary">Login</a>
                    <a href="#" title="Forgot Password?" class="forgot-link">Forgot Password?</a>
                </div>
                <p class="animation-target">Don’t have an account?<a href="#" title="Sign Up">Sign
                        Up</a>
                </p>
            </form>
        </div>
    </div>
    <!-- Login Left End-->

    <!-- Login Right Start-->
    <div class="col d-none d-sm-block">
        <div class="login-right">
            <div class="banner">
                <img src="./assets/images/login-bg.png" alt="We are here">
            </div>
            <div class="content">
                <h3>We are here!</h3>
                <p>Lorem ipsum dolor sit amet
                    concectetur.</p>
            </div>
        </div>
    </div>
    <!-- Login Right Start-->
</div>
