// react-html/src/pages/Dashboard.tsx
import {
  Avatar,
  Button,
  Grid,
  Menu,
  MenuItem,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Typography,
} from "@material-ui/core";
import React from "react";
import { Link } from "react-router-dom";
import {
  ICBoosted,
  ICForSale,
  ICOverview,
  ICVideo,
  ICWip,
  MonthlyVisitors,
  DailyVisitors,
  CountryUsersGraph,
  ICAction,
  ICFilter,
  IDownArrow,
} from "../assets/images";
import Header from "../components/Header";
import Sidebar from "../components/Sidebar";
import { Helmet } from "react-helmet";

function Dashboard() {
  // Menu
  const [menuEl1, setMenuEl1] = React.useState<null | HTMLElement>(null);
  const menuClick1 = (event: React.MouseEvent<HTMLButtonElement>) => {
    setMenuEl1(event.currentTarget);
  };
  const menuClose1 = () => {
    setMenuEl1(null);
  };

  const [menuEl2, setMenuEl2] = React.useState<null | HTMLElement>(null);
  const menuClick2 = (event: React.MouseEvent<HTMLButtonElement>) => {
    setMenuEl2(event.currentTarget);
  };
  const menuClose2 = () => {
    setMenuEl2(null);
  };

  const [menuEl3, setMenuEl3] = React.useState<null | HTMLElement>(null);
  const menuClick3 = (event: React.MouseEvent<HTMLButtonElement>) => {
    setMenuEl3(event.currentTarget);
  };
  const menuClose3 = () => {
    setMenuEl3(null);
  };

  const [menuEl4, setMenuEl4] = React.useState<null | HTMLElement>(null);
  const menuClick4 = (event: React.MouseEvent<HTMLButtonElement>) => {
    setMenuEl4(event.currentTarget);
  };
  const menuClose4 = () => {
    setMenuEl4(null);
  };

  const [menuEl5, setMenuEl5] = React.useState<null | HTMLElement>(null);
  const menuClick5 = (event: React.MouseEvent<HTMLButtonElement>) => {
    setMenuEl5(event.currentTarget);
  };
  const menuClose5 = () => {
    setMenuEl5(null);
  };

  const [menuEl6, setMenuEl6] = React.useState<null | HTMLElement>(null);
  const menuClick6 = (event: React.MouseEvent<HTMLButtonElement>) => {
    setMenuEl6(event.currentTarget);
  };
  const menuClose6 = () => {
    setMenuEl6(null);
  };

  const [menuEl7, setMenuEl7] = React.useState<null | HTMLElement>(null);
  const menuClick7 = (event: React.MouseEvent<HTMLButtonElement>) => {
    setMenuEl7(event.currentTarget);
  };
  const menuClose7 = () => {
    setMenuEl7(null);
  };

  return (
    <>
      <Helmet>
        <title>Dashboard</title>
      </Helmet>
      {/* Wrapper Start */}
      <div className="wrapper">
        <Sidebar />

        <Header />

        <main className="main-content">
          <Grid container spacing={3}>
            <Grid item xs={12} lg={8}>
              {/* Left Content Start */}
              <div className="left-content">
                <div className="boxes">
                  <Grid container spacing={3}>
                    <Grid item xs={6} sm={4} md>
                      <Link
                        to={"/"}
                        title="Overview"
                        className="link-box light-purple"
                      >
                        <Avatar
                          variant="square"
                          src={ICOverview}
                          alt="Overview"
                        />
                        <span>Overview</span>
                      </Link>
                    </Grid>
                    <Grid item xs={6} sm={4} md>
                      <Link
                        to={"/"}
                        title="Videos"
                        className="link-box light-snow"
                      >
                        <Avatar variant="square" src={ICVideo} alt="Videos" />
                        <span>Videos</span>
                      </Link>
                    </Grid>
                    <Grid item xs={6} sm={4} md>
                      <Link
                        to={"/"}
                        title="WIP"
                        className="link-box light-lace"
                      >
                        <Avatar variant="square" src={ICWip} alt="WIP" />
                        <span>WIP</span>
                      </Link>
                    </Grid>
                    <Grid item xs={6} sm={4} md>
                      <Link
                        to={"/"}
                        title="For Sale"
                        className="link-box light-frost"
                      >
                        <Avatar
                          variant="square"
                          src={ICForSale}
                          alt="For Sale"
                        />
                        <span>For Sale</span>
                      </Link>
                    </Grid>
                    <Grid item xs={6} sm={4} md>
                      <Link
                        to={"/"}
                        title="Boosted"
                        className="link-box light-coconut"
                      >
                        <Avatar
                          variant="square"
                          src={ICBoosted}
                          alt="Boosted"
                        />
                        <span>Boosted</span>
                      </Link>
                    </Grid>
                  </Grid>
                </div>
                <div className="primary-box">
                  <div className="top-box pb-36">
                    <div className="content">
                      <Typography variant="h4" className="pb-0">
                        Daily Visitors
                      </Typography>
                      <span className="text-grey">Today vs Yesterday</span>
                    </div>
                    <Grid container spacing={3} className="chart-wrapper">
                      <Grid item xs="auto">
                        <div className="chart-legend">
                          <span className="blue-bg"></span>
                          <em>Yesterday</em>
                        </div>
                      </Grid>
                      <Grid item xs="auto">
                        <div className="chart-legend">
                          <span className="yellow-bg"></span>
                          <em>Today</em>
                        </div>
                      </Grid>
                    </Grid>
                  </div>
                  <Avatar
                    variant="square"
                    src={DailyVisitors}
                    alt="Daily Visitors"
                    className="img-fluid"
                  />
                </div>

                {/* Datatable Start */}
                <Typography variant="h4" className="pb-0">
                  Past Orders
                </Typography>
                <span className="text-grey pb-8">
                  Orders that are Delivered
                </span>
                <TableContainer className="datatable">
                  <Table>
                    <TableHead>
                      <TableRow>
                        <TableCell>Order ID</TableCell>
                        <TableCell>Order Description</TableCell>
                        <TableCell align="center">Quantity</TableCell>
                        <TableCell align="center">Order Date</TableCell>
                        <TableCell align="center">Actions</TableCell>
                      </TableRow>
                    </TableHead>
                    <TableBody>
                      <TableRow>
                        <TableCell>12346</TableCell>
                        <TableCell>
                          Lorem ipsum dolor sit amet consectetur adipisicing
                          elit
                        </TableCell>
                        <TableCell align="center">5</TableCell>
                        <TableCell align="center">12-05-2021</TableCell>
                        <TableCell align="center">
                          <Button aria-haspopup="true" onClick={menuClick1}>
                            <Avatar
                              variant="square"
                              src={ICAction}
                              alt="Action"
                            />
                          </Button>
                          <Menu
                            anchorEl={menuEl1}
                            keepMounted
                            open={Boolean(menuEl1)}
                            onClose={menuClose1}
                            transformOrigin={{
                              horizontal: "right",
                              vertical: "top",
                            }}
                            classes={{
                              paper: "primary-menu",
                            }}
                          >
                            <MenuItem onClick={menuClose1}>Action 1</MenuItem>
                            <MenuItem onClick={menuClose1}>Action 2</MenuItem>
                            <MenuItem onClick={menuClose1}>Action 3</MenuItem>
                          </Menu>
                        </TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>12347</TableCell>
                        <TableCell>
                          Lorem ipsum dolor sit amet consectetur elit
                        </TableCell>
                        <TableCell align="center">2</TableCell>
                        <TableCell align="center">11-04-2021</TableCell>
                        <TableCell align="center">
                          <Button aria-haspopup="true" onClick={menuClick2}>
                            <Avatar
                              variant="square"
                              src={ICAction}
                              alt="Action"
                            />
                          </Button>
                          <Menu
                            anchorEl={menuEl2}
                            keepMounted
                            open={Boolean(menuEl2)}
                            onClose={menuClose2}
                            transformOrigin={{
                              horizontal: "right",
                              vertical: "top",
                            }}
                            classes={{
                              paper: "primary-menu",
                            }}
                          >
                            <MenuItem onClick={menuClose2}>Action 1</MenuItem>
                            <MenuItem onClick={menuClose2}>Action 2</MenuItem>
                            <MenuItem onClick={menuClose2}>Action 3</MenuItem>
                          </Menu>
                        </TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>12348</TableCell>
                        <TableCell>Lorem ipsum dolor sit amet</TableCell>
                        <TableCell align="center">1</TableCell>
                        <TableCell align="center">23-03-2021</TableCell>
                        <TableCell align="center">
                          <Button aria-haspopup="true" onClick={menuClick3}>
                            <Avatar
                              variant="square"
                              src={ICAction}
                              alt="Action"
                            />
                          </Button>
                          <Menu
                            anchorEl={menuEl3}
                            keepMounted
                            open={Boolean(menuEl3)}
                            onClose={menuClose3}
                            transformOrigin={{
                              horizontal: "right",
                              vertical: "top",
                            }}
                            classes={{
                              paper: "primary-menu",
                            }}
                          >
                            <MenuItem onClick={menuClose3}>Action 1</MenuItem>
                            <MenuItem onClick={menuClose3}>Action 2</MenuItem>
                            <MenuItem onClick={menuClose3}>Action 3</MenuItem>
                          </Menu>
                        </TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>123459</TableCell>
                        <TableCell>
                          Lorem ipsum dolor sit amet consectetur adipisicing
                          elit
                        </TableCell>
                        <TableCell align="center">1</TableCell>
                        <TableCell align="center">17-03-2021</TableCell>
                        <TableCell align="center">
                          <Button aria-haspopup="true" onClick={menuClick4}>
                            <Avatar
                              variant="square"
                              src={ICAction}
                              alt="Action"
                            />
                          </Button>
                          <Menu
                            anchorEl={menuEl4}
                            keepMounted
                            open={Boolean(menuEl4)}
                            onClose={menuClose4}
                            transformOrigin={{
                              horizontal: "right",
                              vertical: "top",
                            }}
                            classes={{
                              paper: "primary-menu",
                            }}
                          >
                            <MenuItem onClick={menuClose4}>Action 1</MenuItem>
                            <MenuItem onClick={menuClose4}>Action 2</MenuItem>
                            <MenuItem onClick={menuClose4}>Action 3</MenuItem>
                          </Menu>
                        </TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell>123460</TableCell>
                        <TableCell>
                          Lorem ipsum dolor sit amet consectetur
                        </TableCell>
                        <TableCell align="center">2</TableCell>
                        <TableCell align="center">28-02-2021</TableCell>
                        <TableCell align="center">
                          <Button aria-haspopup="true" onClick={menuClick5}>
                            <Avatar
                              variant="square"
                              src={ICAction}
                              alt="Action"
                            />
                          </Button>
                          <Menu
                            anchorEl={menuEl5}
                            keepMounted
                            transformOrigin={{
                              horizontal: "right",
                              vertical: "top",
                            }}
                            open={Boolean(menuEl5)}
                            onClose={menuClose5}
                            classes={{
                              paper: "primary-menu",
                            }}
                          >
                            <MenuItem onClick={menuClose5}>Action 1</MenuItem>
                            <MenuItem onClick={menuClose5}>Action 2</MenuItem>
                            <MenuItem onClick={menuClose5}>Action 3</MenuItem>
                          </Menu>
                        </TableCell>
                      </TableRow>
                    </TableBody>
                  </Table>
                </TableContainer>
                {/* Datatable End */}
              </div>
              {/* Left Content End */}
            </Grid>

            <Grid item xs={12} lg={4}>
              {/* Right Content Start */}
              <div className="right-content">
                <div className="top-box pb-4">
                  <Typography variant="h4" className="pb-0">
                    Monthly Visitors
                  </Typography>
                  <Button
                    aria-haspopup="true"
                    onClick={menuClick6}
                    className="ml-auto filter-toggle"
                  >
                    <Avatar variant="square" src={ICFilter} alt="Filter" />
                  </Button>
                  <Menu
                    anchorEl={menuEl6}
                    keepMounted
                    open={Boolean(menuEl6)}
                    transformOrigin={{ horizontal: "right", vertical: "top" }}
                    onClose={menuClose6}
                    classes={{
                      paper: "primary-menu",
                    }}
                  >
                    <MenuItem onClick={menuClose6}>Item One</MenuItem>
                    <MenuItem onClick={menuClose6}>Item Two</MenuItem>
                    <MenuItem onClick={menuClose6}>Item Three</MenuItem>
                  </Menu>
                </div>
                <div className="top-content">
                  <Typography variant="h3" className="pb-8 fw-900">
                    1,17,450
                  </Typography>
                  <Grid container spacing={3}>
                    <Grid item xs="auto">
                      <span className="text-grey">Likes / Follows</span>
                    </Grid>
                    <Grid item xs="auto">
                      <span className="text-grey">24,932 / 5,724</span>
                    </Grid>
                  </Grid>
                </div>
                <div className="primary-box">
                  <Button
                    aria-haspopup="true"
                    onClick={menuClick7}
                    className="ml-auto views-toggle"
                  >
                    <span>views</span>
                    <Avatar variant="square" src={IDownArrow} alt="Views" />
                  </Button>
                  <Menu
                    anchorEl={menuEl7}
                    transformOrigin={{ horizontal: "right", vertical: "top" }}
                    keepMounted
                    open={Boolean(menuEl7)}
                    onClose={menuClose7}
                    classes={{
                      paper: "primary-menu",
                    }}
                  >
                    <MenuItem onClick={menuClose7}>Item One</MenuItem>
                    <MenuItem onClick={menuClose7}>Item Two</MenuItem>
                    <MenuItem onClick={menuClose7}>Item Three</MenuItem>
                  </Menu>
                  <Avatar
                    variant="square"
                    src={MonthlyVisitors}
                    alt="Monthly Visitors"
                    className="img-fluid"
                  />
                </div>
                <div className="primary-box country-box mb-0 bb-0">
                  <Typography variant="h4" className="pb-0">
                    By Country
                  </Typography>
                  <span className="text-grey">Top Users By Country</span>
                  <Avatar
                    variant="square"
                    src={CountryUsersGraph}
                    alt="Users By Country"
                    className="img-fluid"
                  />
                  <Grid container spacing={2}>
                    <Grid item xs={6}>
                      <div className="chart-legend">
                        <span className="light-blue-bg"></span>
                        <em>Less users than expected</em>
                      </div>
                    </Grid>
                    <Grid item xs={6}>
                      <div className="chart-legend">
                        <span className="dark-yellow-bg"></span>
                        <em>As per expectation users</em>
                      </div>
                    </Grid>
                    <Grid item xs={6}>
                      <div className="chart-legend">
                        <span className="purple-bg"></span>
                        <em>More users than expected</em>
                      </div>
                    </Grid>
                  </Grid>
                </div>
              </div>
              {/* Right Content Start */}
            </Grid>
          </Grid>
        </main>
      </div>
      {/* Wrapper End */}
    </>
  );
}
export default Dashboard;

// angular-html/src/app/dashboard/dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { Title } from '@angular/platform-browser';
import {
  trigger,
  style,
  transition,
  query,
  stagger,
  useAnimation,
} from '@angular/animations';
import { fadeInAnimation, fadeUpAnimation } from 'src/app/animation';

export interface PeriodicElement {
  orderId: number;
  orderDescription: string;
  quantity: number;
  orderDate: string;
}

const ELEMENT_DATA: PeriodicElement[] = [
  { orderId: 12346, orderDescription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit', quantity: 5, orderDate: '12-05-2021' },
  { orderId: 12347, orderDescription: 'Lorem ipsum dolor sit amet consectetur elit', quantity: 2, orderDate: '11-04-2021' },
  { orderId: 12348, orderDescription: 'Lorem ipsum dolor sit amet', quantity: 1, orderDate: '23-03-2021' },
  { orderId: 123459, orderDescription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit', quantity: 1, orderDate: '17-03-2021' },
  { orderId: 123460, orderDescription: 'Lorem ipsum dolor sit amet consectetur', quantity: 2, orderDate: '28-02-2021' },
];

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: [],
  animations: [
    trigger('animationIn', [
      transition(':enter', [
        query('.animation-fadeIn', [
          style({ opacity: '0' }),
          stagger(120, [
            useAnimation(fadeInAnimation, { params: { duration: '0.4s', delay: '0.3s' } })
          ])
        ])
      ])
    ]),
    trigger('animationChildIn', [
      transition(':enter', [
        query('.animation-target', [
          style({ opacity: '0' }),
          stagger(120, [
            useAnimation(fadeUpAnimation, { params: { duration: '0.6s', delay: '0.3s', offset: '50px' } })
          ])
        ])
      ]),
    ]),
  ]
})

export class DashboardComponent implements OnInit {
  displayedColumns: string[] = ['orderId', 'orderDescription', 'quantity', 'orderDate', 'actions'];
  dataSource = ELEMENT_DATA;
  constructor(public titleService: Title) {
    this.titleService.setTitle("Dashboard");
  }

  ngOnInit(): void {
  }
}

<div class="wrapper">
    <app-sidebar></app-sidebar>
    <app-header></app-header>
    <!-- Main Content Start-->
    <main class="main-content" [@animationIn] [@animationChildIn]>
        <div class="row">
            <div class="col-xl-8">
                <div class="left-content">
                    <div class="boxes">
                        <div class="row">
                            <div class="col-6 col-sm-4 col-md">
                                <a href="#" title="Overview" class="link-box animation-target light-purple">
                                    <img src="./assets/images/ic-overview.svg" alt="Overview">
                                    <span>Overview</span>
                                </a>
                            </div>
                            <div class="col-6 col-sm-4 col-md">
                                <a href="#" title="Videos" class="link-box animation-target light-snow">
                                    <img src="./assets/images/ic-videos.svg" alt="Videos">
                                    <span>Videos</span>
                                </a>
                            </div>
                            <div class="col-6 col-sm-4 col-md">
                                <a href="#" title="WIP" class="link-box animation-target light-lace">
                                    <img src="./assets/images/ic-wip.svg" alt="WIP">
                                    <span>WIP</span>
                                </a>
                            </div>
                            <div class="col-6 col-sm-4 col-md">
                                <a href="#" title="For Sale" class="link-box animation-target light-frost">
                                    <img src="./assets/images/ic-for-sale.svg" alt="For Sale">
                                    <span>For Sale</span>
                                </a>
                            </div>
                            <div class="col-6 col-sm-4 col-md">
                                <a href="#" title="Boosted" class="link-box animation-target light-coconut">
                                    <img src="./assets/images/ic-boosted.svg" alt="Boosted">
                                    <span>Boosted</span>
                                </a>
                            </div>
                        </div>
                    </div>

                    <div class="primary-box animation-fadeIn">
                        <div class="top-box pb-36">
                            <div class="content">
                                <h4 class="pb-0">Daily Visitors</h4>
                                <span class="text-grey">Today vs Yesterday</span>
                            </div>
                            <div class="row ms-auto">
                                <div class="col">
                                    <div class="chart-legend">
                                        <span class="blue-bg"></span>
                                        <em>Yesterday</em>
                                    </div>
                                </div>
                                <div class="col">
                                    <div class="chart-legend">
                                        <span class="yellow-bg"></span>
                                        <em>Today</em>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <img src="./assets/images/daily-visitors.jpg" alt="Daily Visitors" class="img-fluid">
                    </div>

                    <h4 class="pb-0 animation-fadeIn" data-id="1">Past Orders</h4>
                    <span class="text-grey pb-2 animation-fadeIn" data-id="2">Orders that are Delivered</span>
                    <!-- Data Table Start -->
                    <div class="table-responsive animation-fadeIn">
                        <table mat-table [dataSource]="dataSource">
                            <ng-container matColumnDef="orderId">
                                <th mat-header-cell *matHeaderCellDef> Order ID </th>
                                <td mat-cell *matCellDef="let element"> {{element.orderId}} </td>
                            </ng-container>
                            <ng-container matColumnDef="orderDescription">
                                <th mat-header-cell *matHeaderCellDef> Order Description </th>
                                <td mat-cell *matCellDef="let element"> {{element.orderDescription}} </td>
                            </ng-container>
                            <ng-container matColumnDef="quantity">
                                <th mat-header-cell *matHeaderCellDef class="text-center"> Quantity </th>
                                <td mat-cell *matCellDef="let element" class="text-center"> {{element.quantity}} </td>
                            </ng-container>
                            <ng-container matColumnDef="orderDate">
                                <th mat-header-cell *matHeaderCellDef class="text-center"> Order Date </th>
                                <td mat-cell *matCellDef="let element" class="text-center"> {{element.orderDate}} </td>
                            </ng-container>
                            <ng-container matColumnDef="actions">
                                <th mat-header-cell *matHeaderCellDef class="text-center">Actions</th>
                                <td mat-cell *matCellDef="let element" class="text-center">
                                    <button mat-button [matMenuTriggerFor]="actionMenu">
                                        <img src="./assets/images/ic-action.svg" alt="Action">
                                    </button>
                                    <mat-menu #actionMenu="matMenu" xPosition="before">
                                        <button mat-menu-item>Action 1</button>
                                        <button mat-menu-item>Action 2</button>
                                        <button mat-menu-item>Action 3</button>
                                    </mat-menu>
                                </td>
                            </ng-container>
                            <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
                            <tr mat-row *matRowDef="let row; columns: displayedColumns;"></tr>
                        </table>
                    </div>
                    <!-- Data Table End -->
                </div>
            </div>
            <div class="col-xl-4">
                <div class="right-content">
                    <div class="top-box pb-1 animation-fadeIn">
                        <h4 class="pb-0">Monthly Visitors</h4>
                        <button mat-button [matMenuTriggerFor]="filterMenu" class="filter-dropdown  ms-auto">
                            <img src="./assets/images/ic-filter.svg" alt="Filer">
                        </button>
                        <mat-menu #filterMenu="matMenu" xPosition="before">
                            <button mat-menu-item>Item 1</button>
                            <button mat-menu-item>Item 2</button>
                            <button mat-menu-item>Item 3</button>
                        </mat-menu>
                    </div>
                    <div class="top-content animation-fadeIn">
                        <h3 class="pb-2 fw-900">1,17,450</h3>
                        <div class="row">
                            <div class="col-auto">
                                <span class="text-grey">Likes / Follows</span>
                            </div>
                            <div class="col-auto">
                                <span class="text-grey">24,932 / 5,724</span>
                            </div>
                        </div>
                    </div>
                    <div class="primary-box animation-fadeIn">
                        <button mat-button [matMenuTriggerFor]="viewsMenu" class="views-dropdown">
                            <span>views</span>
                            <img src="./assets/images/ic-down-arrow.svg" alt="Down Arrow">
                        </button>
                        <mat-menu #viewsMenu="matMenu" xPosition="before">
                            <button mat-menu-item>Item 1</button>
                            <button mat-menu-item>Item 2</button>
                            <button mat-menu-item>Item 3</button>
                        </mat-menu>
                        <img src="./assets/images/monthly-visitor-graph.jpg" alt="Monthly Visitors" class="img-fluid">
                    </div>
                    <div class="primary-box country-box mb-0 border-bottom-0 animation-fadeIn">
                        <h4 class="pb-0">By Country</h4>
                        <span class="text-grey">Top Users By Country</span>
                        <img src="./assets/images/country-users-graph.jpg" alt="Users By Country" class="img-fluid">
                        <div class="row">
                            <div class="col-6">
                                <div class="chart-legend mb-2">
                                    <span class="light-blue-bg"></span>
                                    <em>Less users than expected</em>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="chart-legend mb-2">
                                    <span class="dark-yellow-bg"></span>
                                    <em>As per expectation users</em>
                                </div>
                            </div>
                            <div class="col-6">
                                <div class="chart-legend mb-2">
                                    <span class="purple-bg"></span>
                                    <em>More users than expected</em>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <!-- Main Content End-->
</div>
